# Generated by Django 6.0.2 on 2026-06-02 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opposed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opposed_by', to='api.element')),
            ],
        ),
        migrations.CreateModel(
            name='Ritual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('effect', models.CharField(max_length=30)),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspect_rituals', to='api.aspect')),
                ('elements', models.ManyToManyField(related_name='element_rituals', to='api.element')),
            ],
        ),
    ]
