# Generated by Django 6.0.2 on 2026-07-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritual',
            name='message1',
            field=models.CharField(default='You discovered', max_length=30),
            preserve_default=False,
        ),
    ]
