# Generated by Django 6.0.2 on 2026-07-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ritual_message1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritual',
            name='outcome_message',
            field=models.CharField(default='Gain BLAH', max_length=30),
            preserve_default=False,
        ),
    ]
